name: Build

on:
    push:
    pull_request:

env:
    PRIMARY_NODEJS_VERSION: 22
    REPORTER: 'min'

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ env.PRIMARY_NODEJS_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.PRIMARY_NODEJS_VERSION }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run lint

    ts-check:
        name: TS check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ env.PRIMARY_NODEJS_VERSION }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.PRIMARY_NODEJS_VERSION }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run ts-check

    unit-tests:
        name: Unit tests
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                node_version:
                    - 16
                    - 18
                    - 20
                    - 22

        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build:transpile
            - run: npm run test

    coverage:
        name: Collect test coverage
        runs-on: ubuntu-latest

        strategy:
            matrix:
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                node_version:
                    - ${{ env.PRIMARY_NODEJS_VERSION }}

        steps:
            - uses: actions/checkout@v2
            - name: Setup node ${{ matrix.node_version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build:transpile
            - run: npm run coverage
            - name: Coveralls parallel
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: node-${{ matrix.node_version }}
                  parallel: true

    send-to-coveralls:
        name: Send coverage to Coveralls
        needs: coverage
        runs-on: ubuntu-latest
        steps:
            - name: Send coverage to Coveralls
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  parallel-finished: true
